dbgapi/win32: Fix NTSTATUS constants
The following patch removes the windef.h include from amd-dbgapi.h.
That alone surprisingly breaks src/os_driver_kmd.cpp, as we'd start
seeing many instances of:

  rocm-dbgapi/src/os_driver_kmd.cpp: In function 'std::string amd::dbgapi::to_string(T) [with T = long int; std::string = std::__cxx11::basic_string<char>]':
  rocm-dbgapi/src/os_driver_kmd.cpp:836:8: error: narrowing conversion of '3221225495' from 'DWORD' {aka 'long unsigned int'} to 'long int' [-Wnarrowing]
    836 |   case STATUS_##x:                                                            \
	|        ^~~~~~~

This is because ntstatus.h and winnt.h define some STATUS constants differently:

  $ grep STATUS_NO_MEMORY /usr/x86_64-w64-mingw32/include/* -rn
  /usr/x86_64-w64-mingw32/include/ntstatus.h:268:#define STATUS_NO_MEMORY ((NTSTATUS)0xC0000017)
  /usr/x86_64-w64-mingw32/include/usbdi.h:28:#define USBD_STATUS_NO_MEMORY ((USBD_STATUS) 0x80000100)
  /usr/x86_64-w64-mingw32/include/winnt.h:1425:#define STATUS_NO_MEMORY ((DWORD)0xC0000017)

NTSTATUS is long, DWORD is unsigned long.

winnt.h does not define all the constants we need.  Also, NTSTATUS is
the one we use throughout src/os_driver_kmd.cpp.

So fix this by telling windows.h to not define the STATUS constants.
That can be done by defining WIN32_NO_STATUS.

With MSVC or clang targeting x86_64-pc-windows-msvc, we need to
explicitly include winternl.h for the NTSTATUS typedef itself.  MinGW
happen to get it automatically via some win32 header including
bcrypt.h.

Ref: https://mschaef.com/windows_h_is_wierd

Change-Id: Ib4f13915cb9de78d4173c47b5ab2aaa4a1ed0447
commit-id:84c49702