[hip-tests] add numa include directory (#3137)
## Motivation

<!-- Explain the purpose of this PR and the goals it aims to achieve.
-->

This change fixes a build error in hip-tests with Spack where `numa.h`
was not found, causing the error:

```
/tmp/root/spack-stage/spack-stage-hip-tests-develop-r2wvnnav27a7xvtkx7epqmsfn3j6fbi2/spack-src/projects/hip-tests/catch/unit/memory/hipMemPrefetchAsync_v2.cc:25:10: fatal error: 'numa.h' file not found
   25 | #include <numa.h>
      |          ^~~~~~~~
```

By adding `target_include_directories(MemoryTest1 PRIVATE
${NUMA_INCLUDE_DIR})`, we ensure the NUMA headers are correctly
included.

`NUMA_INCLUDE_DIR` is set here:

https://github.com/ROCm/rocm-systems/blob/develop/projects/hip-tests/catch/perftests/memory/FindNUMA.cmake#L21

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.