Relax the assertion that the queue must be suspended to inspect the context save user header
The following assertion is raised when running in non-stop mode:

(gdb) set non-stop on
(gdb) run
Starting program: /extra/lmoriche/hip/samples/0_Intro/bit_extract/bit_extract
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5bff700 (LWP 2111827)]
[New Thread 0x7ffef51ff700 (LWP 2111828)]
[Thread 0x7ffef51ff700 (LWP 2111828) exited]
info: running on device #0 AMD Radeon VII
info: allocate host mem (  7.63 MB)
info: allocate device mem (  7.63 MB)
info: copy Host2Device
info: launch 'bit_extract_kernel'
info: copy Device2Host

Thread 4 "bit_extract" hit Breakpoint 1, with lanes [0-63], bit_extract_kernel () at bit_extract.cpp:38
38	    size_t offset = (hipBlockIdx_x * hipBlockDim_x + hipThreadIdx_x);
(gdb) thread 4
[Switching to thread 4, lane 0 (AMDGPU Lane 1:3:1:1/0 (0,0,0)[0,0,0])]
38	    size_t offset = (hipBlockIdx_x * hipBlockDim_x + hipThreadIdx_x);
(gdb) c
Continuing.
fatal error: /extra/lmoriche/gdb/rocm-dbgapi/src/queue.cpp:397: Assertion `state () == state_t::suspended && "the queue must be suspended to read from its context save memory"' failed.

The assertion is protecting accesses to the queue's context save
memory, but in this case, the memory that is being accessed is valid
from the time the queue is created and is never modified until the
queue is destroyed.

This assertion is too strict in this context, and can be safely removed.

Change-Id: I4c13ee2104e33b6f64e0a250f779e42d437cbf09


[ROCm/rocdbgapi commit: 709b484096432cc0e13780df18604c7666ee2d8b]