[RCCL] Fix code coverage build failure (#4098)
## Motivation

RCCL code coverage build fails on ROCm 7.2 and 7.13
```
clang++: error: invalid argument '-fcoverage-mapping' only allowed with '-fprofile-instr-generate'
clang++: error: invalid argument '-fcoverage-mapping' only allowed with '-fprofile-instr-generate'
clang++: error: invalid argument '-fcoverage-mapping' only allowed with '-fprofile-instr-generate'
gmake[2]: *** [src/CMakeFiles/rccl.dir/build.make:1466: src/CMakeFiles/rccl.dir/__/hipify/src/rccl_wrap.cc.o] Error 1
clang++: error: invalid argument '-fcoverage-mapping' only allowed with '-fprofile-instr-generate'
clang++: error: invalid argument '-fcoverage-mapping' only allowed with '-fprofile-instr-generate'
clang++: error: invalid argument '-fcoverage-mapping' only allowed with '-fprofile-instr-generate'
clang++: error: invalid argument '-fcoverage-mapping' only allowed with '-fprofile-instr-generate'
gmake[2]: *** [src/CMakeFiles/rccl.dir/build.make:1438: src/CMakeFiles/rccl.dir/__/hipify/src/msccl.cc.o] Error 1
gmake[2]: *** [src/CMakeFiles/rccl.dir/build.make:1452: src/CMakeFiles/rccl.dir/__/hipify/src/proxy.cc.o] Error 1
gmake[2]: *** [src/CMakeFiles/rccl.dir/build.make:1494: src/CMakeFiles/rccl.dir/__/hipify/src/transport.cc.o] Error 1
gmake[2]: *** [src/CMakeFiles/rccl.dir/build.make:1480: src/CMakeFiles/rccl.dir/__/hipify/src/sym_kernels.cc.o] Error 1
gmake[2]: *** [src/CMakeFiles/rccl.dir/build.make:1508: src/CMakeFiles/rccl.dir/__/hipify/src/device/common.cu.cpp.o] Error 1
clang++: gmake[2]: *** [src/CMakeFiles/rccl.dir/build.make:1522: src/CMakeFiles/rccl.dir/__/hipify/src/device/onerank.cu.cpp.o] Error 1
error: invalid argument '-fcoverage-mapping' only allowed with '-fprofile-instr-generate'
gmake[2]: *** [src/CMakeFiles/rccl.dir/build.make:1536: src/CMakeFiles/rccl.dir/__/hipify/src/graph/connect.cc.o] Error 1
clang++: error: invalid argument '-fcoverage-mapping' only allowed with '-fprofile-instr-generate'
gmake[2]: *** [src/CMakeFiles/rccl.dir/build.make:1550: src/CMakeFiles/rccl.dir/__/hipify/src/graph/paths.cc.o] Error 1
gmake[2]: *** [src/CMakeFiles/rccl.dir/build.make:1564: src/CMakeFiles/rccl.dir/__/hipify/src/graph/rings.cc.o] Error 1
gmake[2]: *** [src/CMakeFiles/rccl.dir/build.make:1578: src/CMakeFiles/rccl.dir/__/hipify/src/graph/rome_models.cc.o] Error 1
gmake[2]: *** [src/CMakeFiles/rccl.dir/build.make:1592: src/CMakeFiles/rccl.dir/__/hipify/src/graph/search.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:203: src/CMakeFiles/rccl.dir/all] Error 2
```

## Technical Details

CMake removes the second occurrence of `-Xarch_host`, producing
`-Xarch_host -fprofile-instr-generate -fcoverage-mapping` instead of
`-Xarch_host -fprofile-instr-generate -Xarch_host -fcoverage-mapping`

Wrapped `-Xarch_host` flag with `SHELL:` prefixes in
`target_compile_options` for the `ENABLE_CODE_COVERAGE` build.

## JIRA ID

AICOMRCCL-724

## Test Plan

- Verify build against different versions of ROCm 
- Verify change against code coverage / debug CI 

## Test Result

Verified code coverage build with ROCm version: 6.4.1, 7.2.1, 7.2.0,
7.13.0

## Submission Checklist

- [ ] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.

Co-authored-by: Arm Patinyasakdikul <arm.patinyasakdikul@amd.com>