[rocprofiler-systems] bump elfutils to 0.195 (#6061)
## Motivation

The purpose of this PR is to bump `elfutils` to latest version 0.195

## Technical Details

In file libdw/dwarf_cu_dwp_section_info.c, variables `offset` and `size`
are seen by GCC 11 as uninitialized, which blocks the build.
`-Wno-error=maybe-uninitialized` solves this.

`-pthread` flag is added to solve `undefined reference to symbol
'pthread_join@@GLIBC_2.2.5'` linking error.

## JIRA ID

AIPROFSYST-405

## Test Plan

- Existing ctests should pass
- Confirming with build logs that new version of ElfUtils is used. 

## Test Result

All existing tests pass

```
  -- [rocprofiler-systems] Attempting to build elfutils(0.195) as external project
  -- [rocprofiler-systems] ElfUtils includes: $<BUILD_INTERFACE:/__w/rocm-systems/rocm-systems/projects/rocprofiler-systems/build/external/elfutils/include>
  -- [rocprofiler-systems] ElfUtils library dirs: $<BUILD_INTERFACE:/__w/rocm-systems/rocm-systems/projects/rocprofiler-systems/build/external/elfutils/lib>
  -- [rocprofiler-systems] ElfUtils libraries: $<BUILD_INTERFACE:/__w/rocm-systems/rocm-systems/projects/rocprofiler-systems/build/external/elfutils/lib/libdw.so>;$<BUILD_INTERFACE:/__w/rocm-systems/rocm-systems/projects/rocprofiler-systems/build/external/elfutils/lib/libelf.so>
```

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.